import React from "react";

const KeyboardIcon = (props) => {
  const { cls } = props;
  return (
    <>
      <mat-icon
        _ngcontent-otter-web-c3819746333=""
        role="img"
        class="mat-icon notranslate mat-icon-no-color"
        aria-hidden="true"
        data-mat-icon-type="svg"
        data-mat-icon-name="keyboard-shortcuts"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="4 6 16 12"
          fit=""
          height="17px"
          width="17px"
          preserveAspectRatio="xMidYMid meet"
          focusable="false"
          className={cls}
        >
          <rect
            x="4.75"
            y="6.75"
            width="14.5"
            height="10.5"
            rx="2.25"
            fill="white"
            stroke="#05294B"
            stroke-width="1.5"
          ></rect>
          <rect
            x="7"
            y="9"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="10"
            y="9"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="13"
            y="9"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="16"
            y="9"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="7"
            y="11.5"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="10"
            y="11.5"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="13"
            y="11.5"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="16"
            y="11.5"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="7"
            y="14"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="10"
            y="14"
            width="4.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
          <rect
            x="16"
            y="14"
            width="1.5"
            height="1.5"
            rx="0.5"
            fill="#05294B"
          ></rect>
        </svg>
      </mat-icon>
    </>
  );
};

export default KeyboardIcon;
